-   id: check-commit-message-is-conventional
    name: Check commit message adheres to Conventional Commit standard
    description: This pre-commit hook checks if the commit message adheres to the Conventional Commit standard, and fails if it doesn't.
    language: python
    entry: check-commit-message .git/COMMIT_EDITMSG
    stages: [commit-msg]
    always_run: true
