name: python-ci

on: [push]

jobs:

  check-semantic-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Set fetch-depth to 0 to fetch all tags (necessary for git-mkver to determine the correct semantic version).
          fetch-depth: 0
      - uses: octue/conventional-commits/check-semantic-version@0.7.1
        with:
          version_source_type: setup.py
